<?php
namespace Waiwaisew\Minifier;
/* =============================================================================
 * PART 2 – VARIABLE MANGLER
 * Renames local variables and parameters inside every function body.
 * ============================================================================= */
class JsMangler
{
    // JS keywords — never usable as variable names
    private const KW = [
        'break','case','catch','class','const','continue','debugger','default',
        'delete','do','else','enum','export','extends','false','finally','for',
        'function','if','implements','import','in','instanceof','interface','let',
        'new','null','package','private','protected','public','return','static',
        'super','switch','this','throw','true','try','typeof','undefined','var',
        'void','while','with','yield','async','await','of','from',
        'arguments','eval','target','meta','as',
    ];

    // Globals / built-ins — never rename even if they appear as local names
    private const PROTECT = [
        'window','document','console','navigator','location','history',
        'screen','performance','crypto','alert','confirm','prompt',
        'setTimeout','setInterval','clearTimeout','clearInterval',
        'requestAnimationFrame','cancelAnimationFrame','queueMicrotask',
        'fetch','XMLHttpRequest','WebSocket','EventSource','Worker',
        'Blob','File','FileReader','FormData',
        'URL','URLSearchParams','Headers','Request','Response',
        'Event','CustomEvent','EventTarget',
        'MutationObserver','IntersectionObserver','ResizeObserver',
        'localStorage','sessionStorage','indexedDB',
        'Math','JSON','Object','Function','Array','String','Number','Boolean',
        'Symbol','BigInt','Date','RegExp','Error','TypeError','RangeError',
        'SyntaxError','ReferenceError','EvalError','URIError',
        'Promise','Proxy','Reflect','Map','Set','WeakMap','WeakSet','WeakRef',
        'ArrayBuffer','DataView','Atomics','SharedArrayBuffer',
        'Int8Array','Uint8Array','Uint8ClampedArray',
        'Int16Array','Uint16Array','Int32Array','Uint32Array',
        'Float32Array','Float64Array','BigInt64Array','BigUint64Array',
        'TextEncoder','TextDecoder','ReadableStream','WritableStream',
        'parseInt','parseFloat','isNaN','isFinite',
        'encodeURIComponent','decodeURIComponent','encodeURI','decodeURI',
        'NaN','Infinity','undefined','null','true','false','globalThis','self',
        '$','jQuery',
        'module','exports','require','process','Buffer','__dirname','__filename',
    ];

    /** @var array[] tokens: ['t'=>type,'v'=>value,'r'=>null|renamed] */
    private array $tok = [];

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    public function mangle(string $code): string
    {
        $this->tok = $this->tokenize($code);
        $this->scanForFunctions(0, count($this->tok) - 1, []);
        return $this->reconstruct();
    }

    // -------------------------------------------------------------------------
    // Tokenizer
    // -------------------------------------------------------------------------

    private function tokenize(string $code): array
    {
        $tokens = [];
        $pos = 0;
        $len = strlen($code);

        while ($pos < $len) {
            $ch = $code[$pos];

            // Skip all whitespace — spacing is regenerated by reconstruct()
            if ($ch === ' ' || $ch === "\t" || $ch === "\n" || $ch === "\r") {
                $pos++;
                continue;
            }

            // --- identifier or keyword ---
            if (preg_match('/[a-zA-Z_$]/', $ch)) {
                $s = $pos;
                while ($pos < $len && preg_match('/[\w$]/', $code[$pos])) $pos++;
                $v = substr($code, $s, $pos - $s);
                $tokens[] = ['t' => in_array($v, self::KW) ? 'kw' : 'id', 'v' => $v, 'r' => null];
                continue;
            }

            // --- number ---
            if (ctype_digit($ch) || ($ch === '.' && isset($code[$pos+1]) && ctype_digit($code[$pos+1]))) {
                $s = $pos;
                if ($ch==='0' && isset($code[$pos+1]) && in_array($code[$pos+1],['x','X','b','B','o','O'])) {
                    $pos += 2;
                    while ($pos<$len && preg_match('/[0-9a-fA-F_]/i',$code[$pos])) $pos++;
                } else {
                    while ($pos<$len && preg_match('/[0-9._]/',$code[$pos])) $pos++;
                    if ($pos<$len && in_array($code[$pos],['e','E'])) {
                        $pos++;
                        if ($pos<$len && in_array($code[$pos],['+','-'])) $pos++;
                        while ($pos<$len && ctype_digit($code[$pos])) $pos++;
                    }
                    if ($pos<$len && $code[$pos]==='n') $pos++; // BigInt
                }
                $tokens[] = ['t'=>'num','v'=>substr($code,$s,$pos-$s),'r'=>null];
                continue;
            }

            // --- quoted string ---
            if ($ch==='"'||$ch==="'") {
                $s=$pos; $q=$ch; $pos++;
                while ($pos<$len) {
                    if ($code[$pos]==='\\') { $pos+=2; continue; }
                    if ($code[$pos]===$q) { $pos++; break; }
                    $pos++;
                }
                $tokens[] = ['t'=>'str','v'=>substr($code,$s,$pos-$s),'r'=>null];
                continue;
            }

            // --- template literal (opaque token, we handle ${} during rename) ---
            if ($ch==='`') {
                $s=$pos++;
                $pos = $this->skipTpl($code,$pos,$len);
                $tokens[] = ['t'=>'tmpl','v'=>substr($code,$s,$pos-$s),'r'=>null];
                continue;
            }

            // --- regex ---
            if ($ch==='/' && $this->isRegexCtx($tokens)) {
                $s=$pos++;
                $inCls=false;
                while ($pos<$len) {
                    $c=$code[$pos];
                    if ($c==='\\') { $pos+=2; continue; }
                    if ($c==='[') { $inCls=true; $pos++; continue; }
                    if ($c===']') { $inCls=false; $pos++; continue; }
                    if ($c==='/'&&!$inCls) { $pos++; break; }
                    $pos++;
                }
                while ($pos<$len && preg_match('/[gimsuy]/',$code[$pos])) $pos++;
                $tokens[] = ['t'=>'rx','v'=>substr($code,$s,$pos-$s),'r'=>null];
                continue;
            }

            // --- multi-char operators ---
            $t3=substr($code,$pos,3); $t2=substr($code,$pos,2);
            if (in_array($t3,['===','!==','**=','&&=','||=','??=','...','>>>','<<=','>>='])) {
                $tokens[]=['t'=>'op','v'=>$t3,'r'=>null]; $pos+=3;
            } elseif (in_array($t2,['=>','==','!=','<=','>=','+=','-=','*=','/=','%=',
                                    '**','&&','||','??','++','--','<<','>>','?.','->'])) {
                $tokens[]=['t'=>'op','v'=>$t2,'r'=>null]; $pos+=2;
            } else {
                $tokens[]=['t'=>'op','v'=>$ch,'r'=>null]; $pos++;
            }
        }

        return $tokens;
    }

    /** Skip to end of template literal (pos is just after opening backtick). Returns pos after closing backtick. */
    private function skipTpl(string $code, int $pos, int $len): int
    {
        while ($pos < $len) {
            $ch = $code[$pos];
            if ($ch==='\\') { $pos+=2; continue; }
            if ($ch==='`') return $pos+1;
            if ($ch==='$'&&($code[$pos+1]??'')==='{') {
                $pos+=2; $depth=1;
                while ($pos<$len&&$depth>0) {
                    $c=$code[$pos];
                    if ($c==='`') { $pos=$this->skipTpl($code,$pos+1,$len); continue; }
                    if ($c==='{') $depth++;
                    elseif ($c==='}') $depth--;
                    $pos++;
                }
                continue;
            }
            $pos++;
        }
        return $pos;
    }

    private function isRegexCtx(array $tokens): bool
    {
        for ($i=count($tokens)-1;$i>=0;$i--) {
            $t=$tokens[$i];
            if ($t['t']==='kw') return in_array($t['v'],['return','typeof','instanceof','in','of','delete','void','throw','new','case','yield','await']);
            if (in_array($t['t'],['id','num'])) return false;
            if ($t['t']==='op') return !in_array($t['v'],[')',']','++','--']);
            break;
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Scope scanner — finds function bodies and triggers mangling
    // -------------------------------------------------------------------------

    /**
     * Scan tokens[s..e] for function scopes and mangle each one.
     * $outerUsed: short names already allocated in ancestor scopes.
     */
    private function scanForFunctions(int $s, int $e, array $outerMap): void
    {
        $i = $s;
        while ($i <= $e) {
            $t = $this->tok[$i];

            // Classic / generator / async function keyword
            if ($t['t']==='kw' && $t['v']==='function') {
                $i = $this->handleFunctionKw($i, $e, $outerMap);
                continue;
            }

            // Arrow function:  =>  followed by  {
            if ($t['t']==='op' && $t['v']=='=>') {
                if (isset($this->tok[$i+1]) && $this->tok[$i+1]['v']==='{') {
                    $params    = $this->arrowParams($i);
                    $bodyEnd   = $this->matchBrace($i+1, $e);
                    $renameMap = $this->mangleFunctionBody($i+2, $bodyEnd-1, $params, $outerMap);
                    // Rename param tokens in the arrow SIGNATURE (before =>)
                    $this->applyMapToArrowSig($i, $renameMap);
                    $i = $bodyEnd+1;
                    continue;
                }
                // Expression-body arrow — no block to mangle
            }

            $i++;
        }
    }

    /** Handle a `function` keyword token and its following body. */
    private function handleFunctionKw(int $kwi, int $e, array $outerMap): int
    {
        $i = $kwi+1;
        if ($i<=$e && $this->tok[$i]['v']==='*') $i++;          // generator *
        if ($i<=$e && $this->tok[$i]['t']==='id') $i++;          // optional name
        if ($i>$e || $this->tok[$i]['v']!=='(') return $i;       // must have (

        $paramOpen = $i;
        $params    = $this->collectParamsFromParen($i, $e);
        $closeP    = $this->matchParen($i, $e);
        $i         = $closeP+1;

        if ($i>$e || $this->tok[$i]['v']!=='{') return $i;       // must have body {

        $bodyEnd   = $this->matchBrace($i, $e);
        $renameMap = $this->mangleFunctionBody($i+1, $bodyEnd-1, $params, $outerMap);
        // Rename param tokens in the function SIGNATURE
        $this->applyMapToParenRange($paramOpen, $closeP, $renameMap);
        return $bodyEnd+1;
    }

    /**
     * Apply renameMap to arrow function param tokens in the signature (before =>).
     * Handles:  (p1, p2) =>   p =>   async (p) =>
     */
    private function applyMapToArrowSig(int $arrowI, array $map): void
    {
        if (empty($map)) return;
        $prev = $arrowI - 1;
        if ($prev >= 0 && $this->tok[$prev]['v'] === ')') {
            // Parenthesised params: find matching (
            $depth = 0; $j = $prev;
            while ($j >= 0) {
                $v = $this->tok[$j]['v'];
                if ($v === ')') $depth++;
                elseif ($v === '(') { $depth--; if ($depth === 0) break; }
                $j--;
            }
            $this->applyMapToParenRange($j, $prev, $map);
        } elseif ($prev >= 0 && $this->tok[$prev]['t'] === 'id') {
            // Single bare param:  p =>
            $n = $this->tok[$prev]['v'];
            if (isset($map[$n])) $this->tok[$prev]['r'] = $map[$n];
        }
    }

    /**
     * Apply renameMap to identifier tokens strictly between $open and $close
     * (a parenthesis range), skipping property accesses and destructuring keys.
     */
    private function applyMapToParenRange(int $open, int $close, array $map): void
    {
        if (empty($map)) return;
        $braceDepth = 0;
        for ($i = $open + 1; $i < $close; $i++) {
            $v = $this->tok[$i]['v'];
            if ($v === '{') { $braceDepth++; continue; }
            if ($v === '}') { $braceDepth--; continue; }

            $tok = &$this->tok[$i];
            if ($tok['t'] !== 'id') continue;
            $v = $tok['v'];
            if (!isset($map[$v])) continue;
            $prev = $i > 0 ? $this->tok[$i-1]['v'] : '';
            $next = $this->tok[$i+1]['v'] ?? '';
            if (in_array($prev, ['.', '?.'])) continue; // property access

            if ($braceDepth > 0) {
                // Inside {} — could be shorthand destructuring pattern
                // Non-shorthand key:  {key: param}  — skip the key
                if ($next === ':' && in_array($prev, ['{', ','])) continue;
                // Shorthand:  {name}  or  {name = default}  → expand
                if (in_array($prev, ['{', ',']) && in_array($next, ['}', ',', '='])) {
                    $tok['r'] = $v . ':' . $map[$v];
                    continue;
                }
            }

            $tok['r'] = $map[$v];
        }
    }

    /**
     * Handles:  (p1, p2) =>   and   p =>   and   async (p) =>
     */
    private function arrowParams(int $arrowI): array
    {
        $prev = $arrowI-1;
        if ($prev >= 0 && $this->tok[$prev]['v']===')') {
            // Find matching (
            $depth=0; $j=$prev;
            while ($j>=0) {
                $v=$this->tok[$j]['v'];
                if ($v===')') $depth++;
                elseif ($v==='(') { $depth--; if ($depth===0) break; }
                $j--;
            }
            return $this->collectParamsFromParen($j, $prev);
        }
        // Single identifier param
        if ($prev>=0 && $this->tok[$prev]['t']==='id') {
            $n=$this->tok[$prev]['v'];
            if (!in_array($n,self::KW)&&!in_array($n,self::PROTECT)) return [$n];
        }
        return [];
    }

    /**
     * Collect parameter names from tokens[openParen..].
     * Handles simple, rest, and basic destructured params.
     */
    private function collectParamsFromParen(int $open, int $limit): array
    {
        $params=[]; $depth=0; $i=$open;
        while ($i<=$limit) {
            $v=$this->tok[$i]['v']; $t=$this->tok[$i]['t'];
            if (in_array($v,['(','[','{'])) $depth++;
            elseif (in_array($v,[')',']','}'])) { $depth--; if ($depth===0) break; }
            elseif ($t==='id') {
                $prev = $i>0 ? $this->tok[$i-1]['v'] : '';
                $next = $this->tok[$i+1]['v'] ?? '';
                // Skip: property access, destructuring key (id followed by :)
                if ($prev!=='.'&&$prev!=='?.'&&$next!==':') {
                    $n=$this->tok[$i]['v'];
                    if (!in_array($n,self::KW)&&!in_array($n,self::PROTECT)) $params[]=$n;
                }
            }
            $i++;
        }
        return array_unique($params);
    }

    // -------------------------------------------------------------------------
    // Core mangler — renames locals in a function body [s..e]
    // -------------------------------------------------------------------------

    /**
     * Mangle all local variables in [s..e].
     *
     * $outerMap : full original→short map from ALL ancestor scopes.
     *
     * Key improvement: restart the short-name counter at 0 for every scope and
     * only avoid short names whose original outer variable is actually referenced
     * (via closure) in this scope. This lets inner scopes freely reuse names like
     * 'a','b','c' that the outer scope used for variables not referenced here —
     * matching the aggressive reuse that Terser/UglifyJS produce.
     */
    private function mangleFunctionBody(int $s, int $e, array $params, array $outerMap): array
    {
        if ($s > $e) return [];

        // Collect everything declared in this scope (not entering nested functions)
        $declared = array_unique(array_merge($params, $this->collectDeclarations($s, $e)));

        // Filter to names that are safe to rename
        $toRename = array_filter($declared, fn($n) =>
            !in_array($n, self::KW) && !in_array($n, self::PROTECT)
        );

        // Names that stay unchanged must not be used as short-name targets
        $notRenamed = array_values(array_diff($declared, $toRename));

        // Only forbid outer short names for variables ACTUALLY referenced here.
        // Outer variables not referenced in this scope are safe to reuse.
        $outerTaken = $this->outerRefsInScope($s, $e, $outerMap, $declared);
        $forbidden  = array_merge($outerTaken, $notRenamed);

        // Assign fresh short names — restart counter at 0 for every scope so
        // every function begins with a,b,c... where possible.
        $taken     = [];
        $renameMap = [];

        foreach ($toRename as $orig) {
            $ni = 0;
            do { $short = self::iToName($ni++); }
            while (in_array($short, self::KW)
                || in_array($short, self::PROTECT)
                || in_array($short, $forbidden)
                || in_array($short, $taken));
            $renameMap[$orig] = $short;
            $taken[] = $short;
        }

        if (empty($renameMap) && empty($outerMap)) {
            // Nothing to rename at all — just recurse into nested scopes
            $this->scanForFunctions($s, $e, $outerMap);
            return [];
        }

        // Full map visible inside this scope: outer context + local renames
        // Local renames override outer names (shadowing).
        $fullMap = array_merge($outerMap, $renameMap);

        // --- Apply renaming to tokens in [s..e], skipping nested function bodies ---
        $nestedBodies = $this->findNestedFunctionBodies($s, $e);
        $skip = [];
        foreach ($nestedBodies as [$ns,$ne]) {
            for ($k=$ns;$k<=$ne;$k++) $skip[$k]=true;
        }

        $braceStack = [];  // stack of 'object'|'block' for every non-skipped {
        for ($i = $s; $i <= $e; $i++) {
            if (isset($skip[$i])) continue;

            $tok = &$this->tok[$i];

            // Track brace type: distinguish code blocks { from object literals {
            if ($tok['t'] === 'op') {
                if ($tok['v'] === '{') {
                    $prevV = $i > 0 ? $this->tok[$i-1]['v'] : '';
                    $prevT = $i > 0 ? $this->tok[$i-1]['t'] : '';
                    // Code block: { after ) closes a control-flow header, or after else/try/finally/do, or after =>
                    $isBlock = $prevV === ')'
                        || $prevV === '=>'
                        || ($prevT === 'kw' && in_array($prevV, ['else','try','finally','do'], true));
                    $braceStack[] = $isBlock ? 'block' : 'object';
                    continue;
                }
                if ($tok['v'] === '}') {
                    array_pop($braceStack);
                    continue;
                }
            }

            // Apply renaming inside template literal ${...} expressions
            if ($tok['t']==='tmpl') {
                $tok['r'] = $this->renameInTemplate($tok['r']??$tok['v'], $fullMap);
                continue;
            }

            if ($tok['t']!=='id') continue;
            $orig = $tok['v'];
            if (!isset($fullMap[$orig])) continue;

            // Skip property access:  obj.name  or  obj?.name
            if ($i > 0 && in_array($this->tok[$i-1]['v'], ['.', '?.'])) continue;

            $prev = $i > 0 ? $this->tok[$i-1]['v'] : '';
            $next = $this->tok[$i+1]['v'] ?? '';

            // Shorthand expansion only inside an object literal {}, never in code blocks
            $inObj = !empty($braceStack) && end($braceStack) === 'object';
            if ($inObj) {
                // Non-shorthand object key:  { key: value }  — skip key, rename value
                if ($next === ':' && in_array($prev, ['{', ','], true)) continue;

                // Shorthand:  {name}  {name,}  {name=default}  → {name:newName}
                if (in_array($prev, ['{', ','], true) && in_array($next, ['}', ',', '='], true)) {
                    $tok['r'] = $orig . ':' . $fullMap[$orig];
                    continue;
                }
            }

            $tok['r'] = $fullMap[$orig];
        }

        // Recurse into nested function bodies passing the full merged map
        $this->scanForFunctions($s, $e, $fullMap);
        return $renameMap;
    }

    /**
     * Scan tokens[s..e] for identifiers that reference outer-scope variables.
     * Returns the SET of short names (values in $outerMap) that are actually
     * used here — these must not be reused as new short names in this scope.
     *
     * Identifiers that are in $localDecl are local declarations (they shadow
     * the outer variable), so their outer short name is NOT marked as taken.
     */
    private function outerRefsInScope(int $s, int $e, array $outerMap, array $localDecl): array
    {
        if (empty($outerMap)) return [];

        $nestedBodies = $this->findNestedFunctionBodies($s, $e);
        $skip = [];
        foreach ($nestedBodies as [$ns,$ne])
            for ($k=$ns;$k<=$ne;$k++) $skip[$k]=true;

        $taken = [];

        for ($i = $s; $i <= $e; $i++) {
            if (isset($skip[$i])) continue;
            $tok = $this->tok[$i];

            // Scan template literal bodies for outer references
            if ($tok['t']==='tmpl') {
                foreach ($outerMap as $origName => $shortName) {
                    if (in_array($origName, $localDecl, true)) continue;
                    if (strpos($tok['v'], $origName) !== false) {
                        $taken[] = $shortName;
                    }
                }
                continue;
            }

            if ($tok['t'] !== 'id') continue;
            $name = $tok['v'];

            // Locally declared: shadows the outer var, outer short name stays free
            if (in_array($name, $localDecl, true)) continue;

            // Skip property accesses — not a variable reference
            if ($i > 0 && in_array($this->tok[$i-1]['v'], ['.', '?.'])) continue;

            if (isset($outerMap[$name])) {
                $taken[] = $outerMap[$name];
            }
        }

        return array_unique($taken);
    }

    // -------------------------------------------------------------------------
    // Declaration collector — gathers var/let/const/catch names at top level
    // -------------------------------------------------------------------------

    private function collectDeclarations(int $s, int $e): array
    {
        $decl = [];
        $skip = [];
        foreach ($this->findNestedFunctionBodies($s,$e) as [$ns,$ne])
            for ($k=$ns;$k<=$ne;$k++) $skip[$k]=true;

        $i = $s;
        while ($i <= $e) {
            if (isset($skip[$i])) { $i++; continue; }
            $t = $this->tok[$i];

            // var / let / const  declaration
            if ($t['t']==='kw' && in_array($t['v'],['var','let','const'])) {
                $j = $i+1;
                if ($j<=$e) {
                    $nt = $this->tok[$j];
                    if ($nt['t']==='id') {
                        // Simple declarator(s): let foo  or  let a=1, b=2, c=3
                        $decl[] = $nt['v'];
                        // Scan ahead for additional comma-separated declarators
                        $k = $j+1; $d2 = 0;
                        while ($k <= $e) {
                            $kv = $this->tok[$k]['v'];
                            if (in_array($kv, ['(','[','{'])) { $d2++; $k++; continue; }
                            if (in_array($kv, [')',']','}'])) {
                                if ($d2 === 0) break; // left the declaration context
                                $d2--; $k++; continue;
                            }
                            if ($d2 === 0 && $kv === ';') break;
                            if ($d2 === 0 && $kv === ',') {
                                $k++;
                                if ($k <= $e && $this->tok[$k]['t'] === 'id')
                                    $decl[] = $this->tok[$k]['v'];
                                continue;
                            }
                            $k++;
                        }
                    } elseif ($nt['v']==='{') {
                        // Object destructuring: let {a, b: localB, ...rest}
                        $depth=0; $k=$j;
                        while ($k<=$e) {
                            $v=$this->tok[$k]['v']; $tt=$this->tok[$k]['t'];
                            if ($v==='{') $depth++;
                            elseif ($v==='}') { $depth--; if($depth===0) break; }
                            elseif ($tt==='id'&&$depth===1) {
                                $nxt=$this->tok[$k+1]['v']??'';
                                $prv=$this->tok[$k-1]['v']??'';
                                if ($prv===':') $decl[]=$this->tok[$k]['v'];      // {key: localName}
                                elseif ($nxt!==':') $decl[]=$this->tok[$k]['v']; // {shorthand}
                            }
                            $k++;
                        }
                    } elseif ($nt['v']==='[') {
                        // Array destructuring: let [a, b, ...rest]
                        $depth=0; $k=$j;
                        while ($k<=$e) {
                            $v=$this->tok[$k]['v']; $tt=$this->tok[$k]['t'];
                            if ($v==='[') $depth++;
                            elseif ($v===']') { $depth--; if($depth===0) break; }
                            elseif ($tt==='id'&&$depth===1) $decl[]=$this->tok[$k]['v'];
                            $k++;
                        }
                    }
                }
            }

            // catch (err)
            if ($t['t']==='kw'&&$t['v']==='catch') {
                if (isset($this->tok[$i+1])&&$this->tok[$i+1]['v']==='('
                 && isset($this->tok[$i+2])&&$this->tok[$i+2]['t']==='id') {
                    $decl[] = $this->tok[$i+2]['v'];
                }
            }

            $i++;
        }

        return array_unique($decl);
    }

    // -------------------------------------------------------------------------
    // Nested function body finder
    // -------------------------------------------------------------------------

    /**
     * Return array of [bodyTokenStart, bodyTokenEnd] for every direct child function
     * body within [s..e] (the { } pairs, inclusive).
     */
    private function findNestedFunctionBodies(int $s, int $e): array
    {
        $bodies = []; $i = $s;
        while ($i <= $e) {
            $t = $this->tok[$i];

            if ($t['t']==='kw' && $t['v']==='function') {
                $j=$i+1;
                if ($j<=$e&&$this->tok[$j]['v']==='*') $j++;
                if ($j<=$e&&$this->tok[$j]['t']==='id') $j++;
                if ($j<=$e&&$this->tok[$j]['v']==='(') {
                    $cp=$this->matchParen($j,$e); $j=$cp+1;
                    if ($j<=$e&&$this->tok[$j]['v']==='{') {
                        $be=$this->matchBrace($j,$e);
                        $bodies[]=[$j,$be]; $i=$be+1; continue;
                    }
                }
            }

            if ($t['t']==='op'&&$t['v']=='=>'&&isset($this->tok[$i+1])&&$this->tok[$i+1]['v']==='{') {
                $be=$this->matchBrace($i+1,$e);
                $bodies[]=[$i+1,$be]; $i=$be+1; continue;
            }

            $i++;
        }
        return $bodies;
    }

    // -------------------------------------------------------------------------
    // Template literal identifier renaming
    // -------------------------------------------------------------------------

    /**
     * Apply $renameMap inside every ${...} expression of a template literal string.
     * Leaves the HTML/text parts between expressions untouched.
     */
    private function renameInTemplate(string $tpl, array $renameMap): string
    {
        $out=''; $pos=0; $len=strlen($tpl);
        while ($pos<$len) {
            $start=strpos($tpl,'${',$pos);
            if ($start===false) { $out.=substr($tpl,$pos); break; }
            $out.=substr($tpl,$pos,$start-$pos);   // text before ${

            // Find matching }
            $depth=0; $j=$start+2;
            while ($j<$len) {
                if ($tpl[$j]==='{') $depth++;
                elseif ($tpl[$j]==='}') { if($depth===0){break;} $depth--; }
                $j++;
            }
            $expr=substr($tpl,$start+2,$j-$start-2);

            // Rename identifiers inside the expression
            foreach ($renameMap as $old=>$new) {
                $expr=preg_replace(
                    '/(?<![a-zA-Z0-9_$])'.preg_quote($old,'/').'(?![a-zA-Z0-9_$])/',
                    $new, $expr
                );
            }

            $out.='${'.$expr.'}';
            $pos=$j+1;
        }
        return $out;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private function matchBrace(int $open, int $limit): int
    {
        $d=0;
        for ($i=$open;$i<=$limit;$i++) {
            $v=$this->tok[$i]['v'];
            if ($v==='{') $d++; elseif ($v==='}') { $d--; if($d===0) return $i; }
        }
        return $limit;
    }

    private function matchParen(int $open, int $limit): int
    {
        $d=0;
        for ($i=$open;$i<=$limit;$i++) {
            $v=$this->tok[$i]['v'];
            if ($v==='(') $d++; elseif ($v===')') { $d--; if($d===0) return $i; }
        }
        return $limit;
    }

    /** 0→a, 1→b, …, 25→z, 26→aa, 27→ab, … */
    private static function iToName(int $i): string
    {
        $c='abcdefghijklmnopqrstuvwxyz';
        if ($i<26) return $c[$i];
        return self::iToName(intdiv($i,26)-1).$c[$i%26];
    }

    private function reconstruct(): string
    {
        $out = '';
        foreach ($this->tok as $t) {
            $v = $t['r'] !== null ? $t['r'] : $t['v'];
            if ($v === '') continue;
            // Re-add space between adjacent word tokens (identifiers, keywords, numbers)
            if ($out !== '') {
                $last  = substr($out, -1);
                $first = $v[0];
                if (preg_match('/[\w$]/', $last) && preg_match('/[\w$]/', $first)) {
                    $out .= ' ';
                }
            }
            $out .= $v;
        }
        return $out;
    }
}
